# This file is based on examples in
# https://docs.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on: [push, pull_request]

jobs:
  Ubuntu:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]

    runs-on: ubuntu-latest

    steps:
    # First print out lots of information. We do this in separate 
    # "name" blocks because otherwise the output gets mixed together
    # in the github actions log.

    - name: Print user and group id
      run: id

    - name: PWD
      run: pwd

    - name: apt-get any needed packages
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential openmpi-bin libopenmpi-dev libblas-dev git cmake libnetcdf-dev

    - name: Print versions
      run: |
        which mpicc
        which mpiexec
        mpicc --version
        cmake --version

    - uses: actions/checkout@v2
      # If we want submodules downloaded, uncomment the next 2 lines:
      #with:
      #  submodules: true

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: which python after python setup
      run: python --version

    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    
    #- name: Install required python packages
    #  run: |
    #    pip install wheel numpy jax jaxlib
    
    - name: env after adding python
      run: env

    - name: Install
      run: pip install -v .

    - name: Try import
      run: python -c "import booz_xform as bx; b = bx.Booz_xform()"

    #- name: Run unit tests
    #  run: python3 -m unittest -v

########################################

  MacOS:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8]

    runs-on: macos-latest

    steps:
    # First print out lots of information. We do this in separate 
    # "name" blocks because otherwise the output gets mixed together
    # in the github actions log.

    - name: Print user and group id
      run: id

    - name: PWD
      run: pwd

    - name: get any needed packages
      run: |
        brew install netcdf
        brew install open-mpi

    - name: Print versions
      run: |
        which mpicc
        which mpiexec
        mpicc --version
        cmake --version

    - uses: actions/checkout@v2
      # If we want submodules downloaded, uncomment the next 2 lines:
      #with:
      #  submodules: true

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: which python after python setup
      run: python --version

    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    
    #- name: Install required python packages
    #  run: |
    #    pip install wheel numpy jax jaxlib
    
    - name: env after adding python
      run: env

    - name: Install
      run: pip install -v .

    - name: Try import
      run: python -c "import booz_xform as bx; b = bx.Booz_xform()"

    #- name: Run unit tests
    #  run: python3 -m unittest -v
